pub const metadata =
    \\<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    \\<?xml-stylesheet type="text/xsl" href="metadata.xsl"?><siardArchive xmlns="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:schemaLocation="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd metadata.xsd">
    \\  <dbname>testnt</dbname>
    \\  <dataOwner>(...)</dataOwner>
    \\  <dataOriginTimespan>2015</dataOriginTimespan>
    \\  <lobFolder>file:///Northwind/</lobFolder>
    \\  <producerApplication>SiardEdit 1.80 Swiss Federal Archives, Berne, Switzerland, 2007-2015</producerApplication> <!-- Modified by Phillip Tømmerholt, Danish National Archives -->
    \\  <archivalDate>2015-11-26</archivalDate>
    \\  <messageDigest>MD53908342CA03FF371BDB9E92427930893</messageDigest>
    \\  <clientMachine>10.50.32.247</clientMachine>
    \\  <databaseProduct>
    \\    Microsoft SQL Server 12.00.2000
    \\  </databaseProduct>
    \\  <connection>jdbc:sqlserver://127.0.0.1:1433; authenticationScheme=nativeAuthentication; xopenStates=false; sendTimeAsDatetime=true; trustServerCertificate=false; sendStringParametersAsUnicode=true; selectMethod=cursor; responseBuffering=adaptive; packetSize=8000; multiSubnetFailover=false; loginTimeout=30; lockTimeout=-1; lastUpdateCount=true; encrypt=false; disableStatementPooling=true; databaseName=NORTHWND; applicationName=Microsoft JDBC Driver for SQL Server; applicationIntent=readwrite;\u0020</connection>
    \\  <databaseUser>ptest2</databaseUser>
    \\  <schemas>
    \\    <schema>
    \\      <name>dbo</name>
    \\      <folder>schema0</folder>
    \\      <tables>
    \\        <table>
    \\          <name>Orders</name>
    \\          <folder>table0</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>OrderID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int identity</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CustomerID</name>
    \\              <type>NATIONAL CHARACTER(5)</type>
    \\              <typeOriginal>nchar(5)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>EmployeeID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>OrderDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>RequiredDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShippedDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipVia</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Freight</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipAddress</name>
    \\              <type>NATIONAL CHARACTER VARYING(60)</type>
    \\              <typeOriginal>nvarchar(60)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipCity</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipRegion</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipPostalCode</name>
    \\              <type>NATIONAL CHARACTER VARYING(10)</type>
    \\              <typeOriginal>nvarchar(10)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipCountry</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_Orders</name>
    \\            <column>OrderID</column>
    \\          </primaryKey>
    \\          <foreignKeys>
    \\            <foreignKey>
    \\              <name>FK_Orders_Customers</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Customers</referencedTable>
    \\              <reference>
    \\                <column>CustomerID</column>
    \\                <referenced>CustomerID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\            <foreignKey>
    \\              <name>FK_Orders_Employees</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Employees</referencedTable>
    \\              <reference>
    \\                <column>EmployeeID</column>
    \\                <referenced>EmployeeID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\            <foreignKey>
    \\              <name>FK_Orders_Shippers</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Shippers</referencedTable>
    \\              <reference>
    \\                <column>ShipVia</column>
    \\                <referenced>ShipperID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\          </foreignKeys>
    \\          <rows>830</rows>
    \\        </table>
    \\          <table>
    \\          <name>Products</name>
    \\          <folder>table1</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>ProductID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int identity</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>SupplierID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CategoryID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>QuantityPerUnit</name>
    \\              <type>NATIONAL CHARACTER VARYING(20)</type>
    \\              <typeOriginal>nvarchar(20)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>UnitPrice</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>UnitsInStock</name>
    \\              <type>SMALLINT</type>
    \\              <typeOriginal>smallint</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>UnitsOnOrder</name>
    \\              <type>SMALLINT</type>
    \\              <typeOriginal>smallint</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ReorderLevel</name>
    \\              <type>SMALLINT</type>
    \\              <typeOriginal>smallint</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Discontinued</name>
    \\              <type>BOOLEAN</type>
    \\              <typeOriginal>bit</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_Products</name>
    \\            <column>ProductID</column>
    \\          </primaryKey>
    \\          <foreignKeys>
    \\            <foreignKey>
    \\              <name>FK_Products_Categories</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Categories</referencedTable>
    \\              <reference>
    \\                <column>CategoryID</column>
    \\                <referenced>CategoryID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\            <foreignKey>
    \\              <name>FK_Products_Suppliers</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Suppliers</referencedTable>
    \\              <reference>
    \\                <column>SupplierID</column>
    \\                <referenced>SupplierID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\          </foreignKeys>
    \\          <rows>77</rows>
    \\        </table>
    \\        <table>
    \\          <name>Categories</name>
    \\          <folder>table2</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>CategoryID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int identity</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CategoryName</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Description</name>
    \\              <type>NATIONAL CHARACTER LARGE OBJECT</type>
    \\              <typeOriginal>ntext</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Picture</name>
    \\              <type>BINARY LARGE OBJECT</type>
    \\              <typeOriginal>image</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_Categories</name>
    \\            <column>CategoryID</column>
    \\          </primaryKey>
    \\          <rows>8</rows>
    \\        </table>
    \\         <table>
    \\          <name>Shippers</name>
    \\          <folder>table3</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>ShipperID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int identity</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CompanyName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Phone</name>
    \\              <type>NATIONAL CHARACTER VARYING(24)</type>
    \\              <typeOriginal>nvarchar(24)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_Shippers</name>
    \\            <column>ShipperID</column>
    \\          </primaryKey>
    \\          <rows>3</rows>
    \\        </table>
    \\        <table>
    \\          <name>Employees</name>
    \\          <folder>table4</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>EmployeeID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int identity</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>LastName</name>
    \\              <type>NATIONAL CHARACTER VARYING(20)</type>
    \\              <typeOriginal>nvarchar(20)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>FirstName</name>
    \\              <type>NATIONAL CHARACTER VARYING(10)</type>
    \\              <typeOriginal>nvarchar(10)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Title</name>
    \\              <type>NATIONAL CHARACTER VARYING(30)</type>
    \\              <typeOriginal>nvarchar(30)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>TitleOfCourtesy</name>
    \\              <type>NATIONAL CHARACTER VARYING(25)</type>
    \\              <typeOriginal>nvarchar(25)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>BirthDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>HireDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Address</name>
    \\              <type>NATIONAL CHARACTER VARYING(60)</type>
    \\              <typeOriginal>nvarchar(60)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>City</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Region</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>PostalCode</name>
    \\              <type>NATIONAL CHARACTER VARYING(10)</type>
    \\              <typeOriginal>nvarchar(10)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Country</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>HomePhone</name>
    \\              <type>NATIONAL CHARACTER VARYING(24)</type>
    \\              <typeOriginal>nvarchar(24)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Extension</name>
    \\              <type>NATIONAL CHARACTER VARYING(4)</type>
    \\              <typeOriginal>nvarchar(4)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Photo</name>
    \\              <type>BINARY LARGE OBJECT</type>
    \\              <typeOriginal>image</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Notes</name>
    \\              <type>NATIONAL CHARACTER LARGE OBJECT</type>
    \\              <typeOriginal>ntext</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ReportsTo</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>PhotoPath</name>
    \\              <type>NATIONAL CHARACTER VARYING(255)</type>
    \\              <typeOriginal>nvarchar(255)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_Employees</name>
    \\            <column>EmployeeID</column>
    \\          </primaryKey>
    \\          <foreignKeys>
    \\            <foreignKey>
    \\              <name>FK_Employees_Employees</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Employees</referencedTable>
    \\              <reference>
    \\                <column>ReportsTo</column>
    \\                <referenced>EmployeeID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\          </foreignKeys>
    \\          <rows>9</rows>
    \\        </table>
    \\         <table>
    \\          <name>Territories</name>
    \\          <folder>table5</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>TerritoryID</name>
    \\              <type>NATIONAL CHARACTER VARYING(20)</type>
    \\              <typeOriginal>nvarchar(20)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>TerritoryDescription</name>
    \\              <type>NATIONAL CHARACTER(50)</type>
    \\              <typeOriginal>nchar(50)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>RegionID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_Territories</name>
    \\            <column>TerritoryID</column>
    \\          </primaryKey>
    \\          <foreignKeys>
    \\            <foreignKey>
    \\              <name>FK_Territories_Region</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Region</referencedTable>
    \\              <reference>
    \\                <column>RegionID</column>
    \\                <referenced>RegionID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\          </foreignKeys>
    \\          <rows>53</rows>
    \\        </table>
    \\        <table>
    \\          <name>CustomerDemographics</name>
    \\          <folder>table6</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>CustomerTypeID</name>
    \\              <type>NATIONAL CHARACTER(10)</type>
    \\              <typeOriginal>nchar(10)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CustomerDesc</name>
    \\              <type>NATIONAL CHARACTER LARGE OBJECT</type>
    \\              <typeOriginal>ntext</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_CustomerDemographics</name>
    \\            <column>CustomerTypeID</column>
    \\          </primaryKey>
    \\          <rows>0</rows>
    \\        </table>
    \\       <table>
    \\          <name>CustomerCustomerDemo</name>
    \\          <folder>table7</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>CustomerID</name>
    \\              <type>NATIONAL CHARACTER(5)</type>
    \\              <typeOriginal>nchar(5)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CustomerTypeID</name>
    \\              <type>NATIONAL CHARACTER(10)</type>
    \\              <typeOriginal>nchar(10)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_CustomerCustomerDemo</name>
    \\            <column>CustomerID</column>
    \\            <column>CustomerTypeID</column>
    \\          </primaryKey>
    \\          <foreignKeys>
    \\            <foreignKey>
    \\              <name>FK_CustomerCustomerDemo</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>CustomerDemographics</referencedTable>
    \\              <reference>
    \\                <column>CustomerTypeID</column>
    \\                <referenced>CustomerTypeID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\            <foreignKey>
    \\              <name>FK_CustomerCustomerDemo_Customers</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Customers</referencedTable>
    \\              <reference>
    \\                <column>CustomerID</column>
    \\                <referenced>CustomerID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\          </foreignKeys>
    \\          <rows>0</rows>
    \\        </table>
    \\        <table>
    \\          <name>Suppliers</name>
    \\          <folder>table8</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>SupplierID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int identity</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CompanyName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ContactName</name>
    \\              <type>NATIONAL CHARACTER VARYING(30)</type>
    \\              <typeOriginal>nvarchar(30)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ContactTitle</name>
    \\              <type>NATIONAL CHARACTER VARYING(30)</type>
    \\              <typeOriginal>nvarchar(30)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Address</name>
    \\              <type>NATIONAL CHARACTER VARYING(60)</type>
    \\              <typeOriginal>nvarchar(60)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>City</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Region</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>PostalCode</name>
    \\              <type>NATIONAL CHARACTER VARYING(10)</type>
    \\              <typeOriginal>nvarchar(10)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Country</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Phone</name>
    \\              <type>NATIONAL CHARACTER VARYING(24)</type>
    \\              <typeOriginal>nvarchar(24)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Fax</name>
    \\              <type>NATIONAL CHARACTER VARYING(24)</type>
    \\              <typeOriginal>nvarchar(24)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>HomePage</name>
    \\              <type>NATIONAL CHARACTER LARGE OBJECT</type>
    \\              <typeOriginal>ntext</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_Suppliers</name>
    \\            <column>SupplierID</column>
    \\          </primaryKey>
    \\          <rows>29</rows>
    \\        </table>
    \\        <table>
    \\          <name>EmployeeTerritories</name>
    \\          <folder>table9</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>EmployeeID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>TerritoryID</name>
    \\              <type>NATIONAL CHARACTER VARYING(20)</type>
    \\              <typeOriginal>nvarchar(20)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_EmployeeTerritories</name>
    \\            <column>EmployeeID</column>
    \\            <column>TerritoryID</column>
    \\          </primaryKey>
    \\          <foreignKeys>
    \\            <foreignKey>
    \\              <name>FK_EmployeeTerritories_Employees</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Employees</referencedTable>
    \\              <reference>
    \\                <column>EmployeeID</column>
    \\                <referenced>EmployeeID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\            <foreignKey>
    \\              <name>FK_EmployeeTerritories_Territories</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Territories</referencedTable>
    \\              <reference>
    \\                <column>TerritoryID</column>
    \\                <referenced>TerritoryID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\          </foreignKeys>
    \\          <rows>49</rows>
    \\        </table>
    \\      <table>
    \\          <name>Customers</name>
    \\          <folder>table10</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>CustomerID</name>
    \\              <type>NATIONAL CHARACTER(5)</type>
    \\              <typeOriginal>nchar(5)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CompanyName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ContactName</name>
    \\              <type>NATIONAL CHARACTER VARYING(30)</type>
    \\              <typeOriginal>nvarchar(30)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ContactTitle</name>
    \\              <type>NATIONAL CHARACTER VARYING(30)</type>
    \\              <typeOriginal>nvarchar(30)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Address</name>
    \\              <type>NATIONAL CHARACTER VARYING(60)</type>
    \\              <typeOriginal>nvarchar(60)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>City</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Region</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>PostalCode</name>
    \\              <type>NATIONAL CHARACTER VARYING(10)</type>
    \\              <typeOriginal>nvarchar(10)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Country</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Phone</name>
    \\              <type>NATIONAL CHARACTER VARYING(24)</type>
    \\              <typeOriginal>nvarchar(24)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Fax</name>
    \\              <type>NATIONAL CHARACTER VARYING(24)</type>
    \\              <typeOriginal>nvarchar(24)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_Customers</name>
    \\            <column>CustomerID</column>
    \\          </primaryKey>
    \\          <rows>91</rows>
    \\        </table>
    \\        <table>
    \\          <name>sysdiagrams</name>
    \\          <folder>table11</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>name</name>
    \\              <type>NATIONAL CHARACTER VARYING(128)</type>
    \\              <typeOriginal>sysname</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>principal_id</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>diagram_id</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int identity</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>version</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>definition</name>
    \\              <type>BINARY LARGE OBJECT</type>
    \\              <typeOriginal>varbinary(2147483647)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK__sysdiagrams__48CFD27E</name>
    \\            <column>diagram_id</column>
    \\          </primaryKey>
    \\          <candidateKeys>
    \\            <candidateKey>
    \\              <name>UK_principal_name</name>
    \\              <column>principal_id</column>
    \\              <column>name</column>
    \\            </candidateKey>
    \\          </candidateKeys>
    \\          <rows>0</rows>
    \\        </table>
    \\        <table>
    \\          <name>Region</name>
    \\          <folder>table12</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>RegionID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>RegionDescription</name>
    \\              <type>NATIONAL CHARACTER(50)</type>
    \\              <typeOriginal>nchar(50)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_Region</name>
    \\            <column>RegionID</column>
    \\          </primaryKey>
    \\          <rows>4</rows>
    \\        </table>
    \\          <table>
    \\          <name>Order Details</name>
    \\          <folder>table13</folder>
    \\          <description/>
    \\          <columns>
    \\            <column>
    \\              <name>OrderID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>UnitPrice</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Quantity</name>
    \\              <type>SMALLINT</type>
    \\              <typeOriginal>smallint</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Discount</name>
    \\              <type>DOUBLE PRECISION</type>
    \\              <typeOriginal>real(7)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\          </columns>
    \\          <primaryKey>
    \\            <name>PK_Order_Details</name>
    \\            <column>OrderID</column>
    \\            <column>ProductID</column>
    \\          </primaryKey>
    \\          <foreignKeys>
    \\            <foreignKey>
    \\              <name>FK_Order_Details_Orders</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Orders</referencedTable>
    \\              <reference>
    \\                <column>OrderID</column>
    \\                <referenced>OrderID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\            <foreignKey>
    \\              <name>FK_Order_Details_Products</name>
    \\              <referencedSchema>dbo</referencedSchema>
    \\              <referencedTable>Products</referencedTable>
    \\              <reference>
    \\                <column>ProductID</column>
    \\                <referenced>ProductID</referenced>
    \\              </reference>
    \\              <deleteAction>RESTRICT</deleteAction>
    \\              <updateAction>RESTRICT</updateAction>
    \\            </foreignKey>
    \\          </foreignKeys>
    \\          <rows>2155</rows>
    \\        </table>
    \\      </tables>
    \\      <views>
    \\        <view>
    \\          <name>Alphabetical list of products</name>
    \\          <columns>
    \\            <column>
    \\              <name>ProductID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>SupplierID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CategoryID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>QuantityPerUnit</name>
    \\              <type>NATIONAL CHARACTER VARYING(20)</type>
    \\              <typeOriginal>nvarchar(20)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>UnitPrice</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>UnitsInStock</name>
    \\              <type>SMALLINT</type>
    \\              <typeOriginal>smallint</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>UnitsOnOrder</name>
    \\              <type>SMALLINT</type>
    \\              <typeOriginal>smallint</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ReorderLevel</name>
    \\              <type>SMALLINT</type>
    \\              <typeOriginal>smallint</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Discontinued</name>
    \\              <type>BOOLEAN</type>
    \\              <typeOriginal>bit</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CategoryName</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Category Sales for 1997</name>
    \\          <columns>
    \\            <column>
    \\              <name>CategoryName</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CategorySales</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Current Product List</name>
    \\          <columns>
    \\            <column>
    \\              <name>ProductID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int identity</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Customer and Suppliers by City</name>
    \\          <columns>
    \\            <column>
    \\              <name>City</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CompanyName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ContactName</name>
    \\              <type>NATIONAL CHARACTER VARYING(30)</type>
    \\              <typeOriginal>nvarchar(30)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Relationship</name>
    \\              <type>CHARACTER VARYING(9)</type>
    \\              <typeOriginal>varchar(9)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Invoices</name>
    \\          <columns>
    \\            <column>
    \\              <name>ShipName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipAddress</name>
    \\              <type>NATIONAL CHARACTER VARYING(60)</type>
    \\              <typeOriginal>nvarchar(60)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipCity</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipRegion</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipPostalCode</name>
    \\              <type>NATIONAL CHARACTER VARYING(10)</type>
    \\              <typeOriginal>nvarchar(10)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipCountry</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CustomerID</name>
    \\              <type>NATIONAL CHARACTER(5)</type>
    \\              <typeOriginal>nchar(5)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CustomerName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Address</name>
    \\              <type>NATIONAL CHARACTER VARYING(60)</type>
    \\              <typeOriginal>nvarchar(60)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>City</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Region</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>PostalCode</name>
    \\              <type>NATIONAL CHARACTER VARYING(10)</type>
    \\              <typeOriginal>nvarchar(10)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Country</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Salesperson</name>
    \\              <type>NATIONAL CHARACTER VARYING(31)</type>
    \\              <typeOriginal>nvarchar(31)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>OrderID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>OrderDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>RequiredDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShippedDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipperName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>UnitPrice</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Quantity</name>
    \\              <type>SMALLINT</type>
    \\              <typeOriginal>smallint</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Discount</name>
    \\              <type>DOUBLE PRECISION</type>
    \\              <typeOriginal>real(7)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ExtendedPrice</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Freight</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Order Details Extended</name>
    \\          <columns>
    \\            <column>
    \\              <name>OrderID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>UnitPrice</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Quantity</name>
    \\              <type>SMALLINT</type>
    \\              <typeOriginal>smallint</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Discount</name>
    \\              <type>DOUBLE PRECISION</type>
    \\              <typeOriginal>real(7)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ExtendedPrice</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Order Subtotals</name>
    \\          <columns>
    \\            <column>
    \\              <name>OrderID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Subtotal</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Orders Qry</name>
    \\          <columns>
    \\            <column>
    \\              <name>OrderID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CustomerID</name>
    \\              <type>NATIONAL CHARACTER(5)</type>
    \\              <typeOriginal>nchar(5)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>EmployeeID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>OrderDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>RequiredDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShippedDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipVia</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Freight</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipAddress</name>
    \\              <type>NATIONAL CHARACTER VARYING(60)</type>
    \\              <typeOriginal>nvarchar(60)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipCity</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipRegion</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipPostalCode</name>
    \\              <type>NATIONAL CHARACTER VARYING(10)</type>
    \\              <typeOriginal>nvarchar(10)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShipCountry</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CompanyName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Address</name>
    \\              <type>NATIONAL CHARACTER VARYING(60)</type>
    \\              <typeOriginal>nvarchar(60)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>City</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Region</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>PostalCode</name>
    \\              <type>NATIONAL CHARACTER VARYING(10)</type>
    \\              <typeOriginal>nvarchar(10)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Country</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Product Sales for 1997</name>
    \\          <columns>
    \\            <column>
    \\              <name>CategoryName</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductSales</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Products Above Average Price</name>
    \\          <columns>
    \\            <column>
    \\              <name>ProductName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>UnitPrice</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Products by Category</name>
    \\          <columns>
    \\            <column>
    \\              <name>CategoryName</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>QuantityPerUnit</name>
    \\              <type>NATIONAL CHARACTER VARYING(20)</type>
    \\              <typeOriginal>nvarchar(20)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>UnitsInStock</name>
    \\              <type>SMALLINT</type>
    \\              <typeOriginal>smallint</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Discontinued</name>
    \\              <type>BOOLEAN</type>
    \\              <typeOriginal>bit</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Quarterly Orders</name>
    \\          <columns>
    \\            <column>
    \\              <name>CustomerID</name>
    \\              <type>NATIONAL CHARACTER(5)</type>
    \\              <typeOriginal>nchar(5)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CompanyName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>City</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Country</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Sales Totals by Amount</name>
    \\          <columns>
    \\            <column>
    \\              <name>SaleAmount</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>OrderID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CompanyName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ShippedDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Sales by Category</name>
    \\          <columns>
    \\            <column>
    \\              <name>CategoryID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>CategoryName</name>
    \\              <type>NATIONAL CHARACTER VARYING(15)</type>
    \\              <typeOriginal>nvarchar(15)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductName</name>
    \\              <type>NATIONAL CHARACTER VARYING(40)</type>
    \\              <typeOriginal>nvarchar(40)</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>ProductSales</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Summary of Sales by Quarter</name>
    \\          <columns>
    \\            <column>
    \\              <name>ShippedDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>OrderID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Subtotal</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\        <view>
    \\          <name>Summary of Sales by Year</name>
    \\          <columns>
    \\            <column>
    \\              <name>ShippedDate</name>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\            <column>
    \\              <name>OrderID</name>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\              <nullable>false</nullable>
    \\            </column>
    \\            <column>
    \\              <name>Subtotal</name>
    \\              <type>DECIMAL(19,4)</type>
    \\              <typeOriginal>money</typeOriginal>
    \\              <nullable>true</nullable>
    \\            </column>
    \\          </columns>
    \\        </view>
    \\      </views>
    \\      <routines>
    \\        <routine>
    \\          <name>CustOrderHist</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>CustomerID</name>
    \\              <mode>IN</mode>
    \\              <type>NATIONAL CHARACTER(10)</type>
    \\              <typeOriginal>nchar</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>CustOrdersDetail</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>OrderID</name>
    \\              <mode>IN</mode>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>CustOrdersOrders</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>CustomerID</name>
    \\              <mode>IN</mode>
    \\              <type>NATIONAL CHARACTER(10)</type>
    \\              <typeOriginal>nchar</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>Employee Sales by Country</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>Beginning_Date</name>
    \\              <mode>IN</mode>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>Ending_Date</name>
    \\              <mode>IN</mode>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>Sales by Year</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>Beginning_Date</name>
    \\              <mode>IN</mode>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>Ending_Date</name>
    \\              <mode>IN</mode>
    \\              <type>TIMESTAMP(7)</type>
    \\              <typeOriginal>datetime</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>SalesByCategory</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>CategoryName</name>
    \\              <mode>IN</mode>
    \\              <type>NATIONAL CHARACTER VARYING(30)</type>
    \\              <typeOriginal>nvarchar</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>OrdYear</name>
    \\              <mode>IN</mode>
    \\              <type>NATIONAL CHARACTER VARYING(8)</type>
    \\              <typeOriginal>nvarchar</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>Ten Most Expensive Products</name>
    \\        </routine>
    \\        <routine>
    \\          <name>fn_diagramobjects</name>
    \\        </routine>
    \\        <routine>
    \\          <name>sp_alterdiagram</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>diagramname</name>
    \\              <mode>IN</mode>
    \\              <type>NATIONAL CHARACTER VARYING(256)</type>
    \\              <typeOriginal>sysname</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>owner_id</name>
    \\              <mode>IN</mode>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>version</name>
    \\              <mode>IN</mode>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>definition</name>
    \\              <mode>IN</mode>
    \\              <type>BINARY LARGE OBJECT</type>
    \\              <typeOriginal>varbinary</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>sp_creatediagram</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>diagramname</name>
    \\              <mode>IN</mode>
    \\              <type>NATIONAL CHARACTER VARYING(256)</type>
    \\              <typeOriginal>sysname</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>owner_id</name>
    \\              <mode>IN</mode>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>version</name>
    \\              <mode>IN</mode>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>definition</name>
    \\              <mode>IN</mode>
    \\              <type>BINARY LARGE OBJECT</type>
    \\              <typeOriginal>varbinary</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>sp_dropdiagram</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>diagramname</name>
    \\              <mode>IN</mode>
    \\              <type>NATIONAL CHARACTER VARYING(256)</type>
    \\              <typeOriginal>sysname</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>owner_id</name>
    \\              <mode>IN</mode>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>sp_helpdiagramdefinition</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>diagramname</name>
    \\              <mode>IN</mode>
    \\              <type>NATIONAL CHARACTER VARYING(256)</type>
    \\              <typeOriginal>sysname</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>owner_id</name>
    \\              <mode>IN</mode>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>sp_helpdiagrams</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>diagramname</name>
    \\              <mode>IN</mode>
    \\              <type>NATIONAL CHARACTER VARYING(256)</type>
    \\              <typeOriginal>sysname</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>owner_id</name>
    \\              <mode>IN</mode>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>sp_renamediagram</name>
    \\          <parameters>
    \\            <parameter>
    \\              <name>diagramname</name>
    \\              <mode>IN</mode>
    \\              <type>NATIONAL CHARACTER VARYING(256)</type>
    \\              <typeOriginal>sysname</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>owner_id</name>
    \\              <mode>IN</mode>
    \\              <type>INTEGER</type>
    \\              <typeOriginal>int</typeOriginal>
    \\            </parameter>
    \\            <parameter>
    \\              <name>new_diagramname</name>
    \\              <mode>IN</mode>
    \\              <type>NATIONAL CHARACTER VARYING(256)</type>
    \\              <typeOriginal>sysname</typeOriginal>
    \\            </parameter>
    \\          </parameters>
    \\        </routine>
    \\        <routine>
    \\          <name>sp_upgraddiagrams</name>
    \\        </routine>
    \\      </routines>
    \\    </schema>
    \\  </schemas>
    \\  <users>
    \\    <user>
    \\      <name>PTEST2</name>
    \\    </user>
    \\  </users>
    \\  <roles>
    \\    <role>
    \\      <name>DB_DATAREADER</name>
    \\      <admin/>
    \\    </role>
    \\    <role>
    \\      <name>PUBLIC</name>
    \\      <admin/>
    \\    </role>
    \\  </roles>
    \\</siardArchive>
;
